### PR TITLE
[Doc][Spark] Update the doc: fix the outdated argument annotations and typo

### LINKED ISSUE #253: [Doc]: The args of method annotations  is inconsistent with the real args of the method
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

com.alibaba.graphar.util.FileSystem.scala
def writeDataFrame(...){}
image
The args of method annotations  is inconsistent with the real args of the method,in the ide will give red

### Expected Behavior

 args in the annotation of the method are kept consistent with the true args

### Minimal Reproducible Example

/**
   * Write input dataframe to output path with certain file format.
   *
   * **@param dataframe**
   *   DataFrame to write out.
   * @param fileType
   *   output file format type, the value could be csv|parquet|orc.
   * @param outputPrefix
   *   output path prefix.
   * **@param startChunkIndex**
   *   the start index of chunk.
   */
  def writeDataFrame(
      dataFrame: DataFrame,
      fileType: String,
      outputPrefix: String,
      offsetStartChunkIndex: Option[Int],
      aggNumListOfEdgeChunk: Option[Array[Long]]
  ): Unit = {...

### Environment

- Operating system:mac 
- GraphAr version:main

### Link to GraphAr Logs

_No response_

### Further Information

_No response_

### PR DESCRIPTION
**Pull request by acezen**
## Proposed changes
as title.

## Types of changes

What types of changes does your code introduce to GraphAr?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/alibaba/GraphAr/blob/main/CONTRIBUTING.rst) doc
- [ ] I have signed the CLA
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

## Further comments
close #253

### CODE REVIEW

File: spark/src/main/scala/com/alibaba/graphar/util/FileSystem.scala [hunk 1]
```diff
@@ -25,20 +25,24 @@ import org.apache.hadoop.conf.Configuration
...
-/** Helper object to write dataframe to chunk files */
+/** Helper object to write DataFrame to chunk files */
 object FileSystem {
 
   /**
-   * Write input dataframe to output path with certain file format.
+   * Write input DataFrame to output path with certain file format.
    *
-   * @param dataframe
+   * @param dataFrame
```
Comment (lixueclaire) [inline spark/src/main/scala/com/alibaba/graphar/util/FileSystem.scala:34]: DataFrame

Comment (acezen) [reply spark/src/main/scala/com/alibaba/graphar/util/FileSystem.scala:34]: the parameter name is `dataFrame`
